export const ClinicalTrialStatusEnum = {
    COMPLETED: "COMPLETED",
    NOT_YET_RECRUITING: "NOT_YET_RECRUITING",
    UNKNOWN: "UNKNOWN",
    ACTIVE_NOT_RECRUITING: "ACTIVE_NOT_RECRUITING",
    WITHDRAWN: "WITHDRAWN",
    TERMINATED: "TERMINATED",
    RECRUITING: "RECRUITING",
    SUSPENDED: "SUSPENDED",
    ENROLLING_BY_INVITATION: "ENROLLING_BY_INVITATION",
    // APPROVED_FOR_MARKETING: "APPROVED_FOR_MARKETING",
    // NO_LONGER_AVAILABLE: "NO_LONGER_AVAILABLE",
    // TEMPORARILY_NOT_AVAILABLE: "TEMPORARILY_NOT_AVAILABLE",
} as const;
